USE MWS
GO

DROP PROCEDURE IF EXISTS dbo.Wiadomosc_Insert
DROP PROCEDURE IF EXISTS dbo.Wiadomosc_Update
DROP PROCEDURE IF EXISTS dbo.Wiadomosc_Delete
DROP PROCEDURE IF EXISTS dbo.Wiadomosc_GetRecord
DROP PROCEDURE IF EXISTS dbo.Wiadomosc_GetRecordById
DROP PROCEDURE IF EXISTS dbo.Wiadomosc_GetCollection
DROP PROCEDURE IF EXISTS dbo.Uczestnik_Insert
DROP PROCEDURE IF EXISTS dbo.Uczestnik_Update
DROP PROCEDURE IF EXISTS dbo.Uczestnik_Delete
DROP PROCEDURE IF EXISTS dbo.Uczestnik_GetRecord
DROP PROCEDURE IF EXISTS dbo.Uczestnik_GetRecordById
DROP PROCEDURE IF EXISTS dbo.Uczestnik_GetCollection
DROP PROCEDURE IF EXISTS dbo.Wydarzenie_Insert
DROP PROCEDURE IF EXISTS dbo.Wydarzenie_Update
DROP PROCEDURE IF EXISTS dbo.Wydarzenie_Delete
DROP PROCEDURE IF EXISTS dbo.Wydarzenie_GetRecord
DROP PROCEDURE IF EXISTS dbo.Wydarzenie_GetRecordById
DROP PROCEDURE IF EXISTS dbo.Wydarzenie_GetCollection
DROP PROCEDURE IF EXISTS dbo.Logowanie_Logowanie_Insert
DROP PROCEDURE IF EXISTS dbo.Logowanie_Logowanie_Delete
DROP PROCEDURE IF EXISTS dbo.Logowanie_Logowanie_GetCollection
DROP PROCEDURE IF EXISTS dbo.Pracownik_Pracownik_Insert
DROP PROCEDURE IF EXISTS dbo.Pracownik_Pracownik_Delete
DROP PROCEDURE IF EXISTS dbo.Pracownik_Pracownik_GetCollection
DROP PROCEDURE IF EXISTS dbo.Uczestnik_Bilet_Insert
DROP PROCEDURE IF EXISTS dbo.Uczestnik_Bilet_Delete
DROP PROCEDURE IF EXISTS dbo.Uczestnik_Bilet_GetCollection
DROP PROCEDURE IF EXISTS dbo.Wydarzenie_Sponsor_Insert
DROP PROCEDURE IF EXISTS dbo.Wydarzenie_Sponsor_Delete
DROP PROCEDURE IF EXISTS dbo.Wydarzenie_Sponsor_GetCollection
DROP PROCEDURE IF EXISTS dbo.Wydarzenie_Pracownik_Insert
DROP PROCEDURE IF EXISTS dbo.Wydarzenie_Pracownik_Delete
DROP PROCEDURE IF EXISTS dbo.Wydarzenie_Pracownik_GetCollection
DROP PROCEDURE IF EXISTS dbo.Wydarzenie_Uczestnik_Insert
DROP PROCEDURE IF EXISTS dbo.Wydarzenie_Uczestnik_Delete
DROP PROCEDURE IF EXISTS dbo.Wydarzenie_Uczestnik_GetCollection
DROP PROCEDURE IF EXISTS dbo.Wniosek_Insert
DROP PROCEDURE IF EXISTS dbo.Wniosek_Update
DROP PROCEDURE IF EXISTS dbo.Wniosek_Delete
DROP PROCEDURE IF EXISTS dbo.Wniosek_GetRecord
DROP PROCEDURE IF EXISTS dbo.Wniosek_GetRecordById
DROP PROCEDURE IF EXISTS dbo.Wniosek_GetCollection
DROP PROCEDURE IF EXISTS dbo.Sponsor_Insert
DROP PROCEDURE IF EXISTS dbo.Sponsor_Update
DROP PROCEDURE IF EXISTS dbo.Sponsor_Delete
DROP PROCEDURE IF EXISTS dbo.Sponsor_GetRecord
DROP PROCEDURE IF EXISTS dbo.Sponsor_GetRecordById
DROP PROCEDURE IF EXISTS dbo.Sponsor_GetCollection
DROP PROCEDURE IF EXISTS dbo.Logowanie_Insert
DROP PROCEDURE IF EXISTS dbo.Logowanie_Update
DROP PROCEDURE IF EXISTS dbo.Logowanie_Delete
DROP PROCEDURE IF EXISTS dbo.Logowanie_GetRecord
DROP PROCEDURE IF EXISTS dbo.Logowanie_GetRecordById
DROP PROCEDURE IF EXISTS dbo.Logowanie_GetCollection
DROP PROCEDURE IF EXISTS dbo.Logowanie_CheckCredentials
DROP PROCEDURE IF EXISTS dbo.Kontakt_Insert;
DROP PROCEDURE IF EXISTS dbo.Kontakt_Update
DROP PROCEDURE IF EXISTS dbo.Kontakt_Delete
DROP PROCEDURE IF EXISTS dbo.Kontakt_GetRecord
DROP PROCEDURE IF EXISTS dbo.Kontakt_GetRecordById
DROP PROCEDURE IF EXISTS dbo.Kontakt_GetCollection
DROP PROCEDURE IF EXISTS dbo.KartaPlatnicza_Insert
DROP PROCEDURE IF EXISTS dbo.KartaPlatnicza_Update
DROP PROCEDURE IF EXISTS dbo.KartaPlatnicza_Delete
DROP PROCEDURE IF EXISTS dbo.KartaPlatnicza_GetRecord
DROP PROCEDURE IF EXISTS dbo.KartaPlatnicza_GetRecordById
DROP PROCEDURE IF EXISTS dbo.KartaPlatnicza_GetCollection
DROP PROCEDURE IF EXISTS dbo.Dotacja_Insert
DROP PROCEDURE IF EXISTS dbo.Dotacja_Update
DROP PROCEDURE IF EXISTS dbo.Dotacja_Delete
DROP PROCEDURE IF EXISTS dbo.Dotacja_GetRecord
DROP PROCEDURE IF EXISTS dbo.Dotacja_GetRecordById
DROP PROCEDURE IF EXISTS dbo.Dotacja_GetCollection
DROP PROCEDURE IF EXISTS dbo.Bilet_Insert
DROP PROCEDURE IF EXISTS dbo.Bilet_Update
DROP PROCEDURE IF EXISTS dbo.Bilet_Delete
DROP PROCEDURE IF EXISTS dbo.Bilet_GetRecord
DROP PROCEDURE IF EXISTS dbo.Bilet_GetRecordById
DROP PROCEDURE IF EXISTS dbo.Bilet_GetCollection
DROP PROCEDURE IF EXISTS dbo.Pracownik_Insert
DROP PROCEDURE IF EXISTS dbo.Pracownik_Update
DROP PROCEDURE IF EXISTS dbo.Pracownik_Delete
DROP PROCEDURE IF EXISTS dbo.Pracownik_GetRecord
DROP PROCEDURE IF EXISTS dbo.Pracownik_GetRecordById
DROP PROCEDURE IF EXISTS dbo.Pracownik_GetCollection
DROP PROCEDURE IF EXISTS dbo.Platnosc_Insert
DROP PROCEDURE IF EXISTS dbo.Platnosc_Update
DROP PROCEDURE IF EXISTS dbo.Platnosc_Delete
DROP PROCEDURE IF EXISTS dbo.Platnosc_GetRecord
DROP PROCEDURE IF EXISTS dbo.Platnosc_GetRecordById
DROP PROCEDURE IF EXISTS dbo.Platnosc_GetCollection
GO